apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: mysql
    spec:
      hostname: mysql
      containers:
        - name: mysql
          image: mysql:5.7
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_USER
              value: root
            - name: MYSQL_DATABASE
              value: local_db 
            - name: MYSQL_ROOT_PASSWORD
              value: pwned
          ports:
            - name: mysql
              protocol: TCP
              containerPort: 3306
          resources: 
            requests: 
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 600Mi
          volumeMounts:
            - name: mysql-pv
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc

