apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: demucs-worker
spec:
  selector:
    matchLabels:
      app: demucs-worker
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: demucs-worker
    spec:
      containers:
      - name: demucs-worker
        image: siddharths2710/demucs-worker:1.0.0
        resources:
          limits:
            memory: "4Gi"
            cpu: "2200m"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: MINIO_HOST
          value: minio
        - name: MINIO_PORT
          value: "9000"
        - name: MINIO_USER
          value: "rootuser"
        - name: MINIO_PASS
          value: "rootpass123"
