apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: pwdcrkaas-worker
spec:
  selector:
    matchLabels:
      app: pwdcrkaas-worker
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: pwdcrkaas-worker
    spec:
      containers:
      - name: pwdcrkaas-worker
        image: siddharths2710/pwdcrkaas-worker:1.0.0
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        resources:
          limits:
            memory: "2Gi"
            cpu: "1700m"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: MINIO_HOST
          value: minio
        - name: MINIO_PORT
          value: "9000"
        - name: MINIO_USER
          value: "rootuser"
        - name: MINIO_PASS
          value: "rootpass123"