FROM python:3.9-alpine

RUN pip3 install flask Flask-Debug redis jsonpickle requests minio sqlalchemy

RUN mkdir -p /svr/app
COPY app /svr/app
COPY app.sh /svr

EXPOSE 5000
# WORKDIR /
# CMD   FLASK_APP=app flask run -h 0.0.0.0

ENV FLASK_PORT 5000
CMD [ "/bin/sh", "-x", "/app/app.sh" ]
