apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: pwdcrkaas-rest
spec:
  selector:
    matchLabels:
      app: pwdcrkaas-rest
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: pwdcrkaas-rest
    spec:
      containers:
      - name: pwdcrkaas-rest
        image: siddharths2710/pwdcrkaas-rest:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
        env:
        - name: FLASK_PORT
          value: "5000"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: MINIO_HOST
          value: minio
        - name: MINIO_PORT
          value: "9000"
        - name: MINIO_USER
          value: "rootuser"
        - name: MINIO_PWD
          value: "rootpass123"
