apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: pwdcrkaas-rest
spec:
  selector:
    matchLabels:
      app: pwdcrkaas-rest
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: pwdcrkaas-rest
    spec:
      containers:
      - name: pwdcrkaas-rest
        image: shreyash14s/pwdcrkaas-rest:1.0.0
        resources:
          limits:
            memory: "2048Mi"
            cpu: "500m"
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
        env:
        - name: FLASK_PORT
          value: "5000"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: MINIO_SERVICE_HOST
          value: minio
        - name: MINIO_SERVICE_PORT
          value: "9000"
        - name: MINIO_SERVICE_USER
          value: "rootuser"
        - name: MINIO_SERVICE_PASS
          value: "rootpass123"
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DB
          value: "local_db"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PWD
          value: "pwned"
